import { readFile, writeFile, rename, mkdir, symlink, lstat, readlink, unlink } from "node:fs/promises";
import { homedir } from "node:os";
import { join, dirname } from "node:path";
import { mergeHooks } from "./settings-merge";
import { paths } from "../lib/paths";

export interface InstallPaths {
  repoRoot: string;
  settingsPath: string;
  hookMainPath: string;
  skillSrcDir: string;
  skillDestDir: string;
  localBinDir: string;
  bunPath: string;
}

/** `project: true` scopes settings + skill to `<cwd>/.claude` instead of `~/.claude`, so the
 * hooks only fire for sessions started inside that project. `hookMainPath` and `localBinDir`
 * stay machine-global either way — the hook script and the CLI/wrapper binaries are shared
 * tooling, not something that makes sense to duplicate per project. */
export function defaultInstallPaths(opts: { project?: boolean; cwd?: string } = {}): InstallPaths {
  const repoRoot = join(import.meta.dir, "..", "..");
  const claudeDir = opts.project ? join(opts.cwd ?? process.cwd(), ".claude") : join(homedir(), ".claude");
  return {
    repoRoot,
    settingsPath: join(claudeDir, "settings.json"),
    hookMainPath: join(repoRoot, "src", "hooks", "main.ts"),
    skillSrcDir: join(repoRoot, "assets", "skills", "sync"),
    skillDestDir: join(claudeDir, "skills", "sync"),
    localBinDir: join(homedir(), ".local", "bin"),
    bunPath: process.execPath,
  };
}

/** Marks a generated (non-symlink) file under localBinDir as ours, so uninstall recognizes
 * it and a re-install knows it's safe to overwrite. */
export const WRAPPER_SENTINEL = "# claude-sync generated wrapper";

/** `claude-sync`/`csync` are installed as generated wrapper scripts, not symlinks into
 * `bin/`, because their old `#!/usr/bin/env bun` shebang depended on `bun` being on
 * `PATH` — which a non-interactive or non-login shell won't have if bun's installer only
 * added it to `.zshrc` (the same class of bug fixed for hooks in settings-merge.ts). Baking
 * the resolved bun path directly into the wrapper removes that dependency entirely. */
function claudeSyncWrapperContents(bunPath: string, repoRoot: string): string {
  const cliPath = join(repoRoot, "src", "cli.ts");
  return `#!/bin/sh\n${WRAPPER_SENTINEL}\n# Bakes an absolute bun path so this runs regardless of the caller's PATH.\n# Generated by \`claude-sync install\` — re-run install to regenerate after moving bun.\nexec "${bunPath}" "${cliPath}" "$@"\n`;
}

function csyncWrapperContents(localBinDir: string): string {
  const claudeSyncBin = join(localBinDir, "claude-sync");
  return [
    "#!/bin/sh",
    WRAPPER_SENTINEL,
    "# Launch a claude session joined to a sync group. Plain `claude` is never affected —",
    "# CLAUDE_SYNC_GROUP is what the hook guard checks first, and only this wrapper sets it.",
    "set -eu",
    "",
    'if [ -z "${1:-}" ]; then',
    '  echo "usage: csync <group> [claude args...]" >&2',
    "  exit 2",
    "fi",
    "",
    'group="$1"',
    "shift",
    "",
    `"${claudeSyncBin}" daemon ensure >/dev/null 2>&1 &`,
    "",
    'CLAUDE_SYNC_GROUP="$group" exec claude "$@"',
    "",
  ].join("\n");
}

async function backupAndWriteSettings(settingsPath: string, next: unknown): Promise<void> {
  let raw: string | undefined;
  try {
    raw = await readFile(settingsPath, "utf8");
  } catch {
    raw = undefined;
  }
  if (raw !== undefined) {
    await writeFile(`${settingsPath}.claude-sync.bak.${Date.now()}`, raw);
  }
  await mkdir(dirname(settingsPath), { recursive: true });
  const tmp = `${settingsPath}.tmp.${process.pid}`;
  await writeFile(tmp, JSON.stringify(next, null, 2));
  await rename(tmp, settingsPath);
}

/** Create (or repair) a symlink at linkPath -> target. Refuses to touch a real file/dir
 * that isn't already a symlink we recognize, so install never clobbers unrelated state. */
async function ensureSymlink(target: string, linkPath: string): Promise<void> {
  await mkdir(dirname(linkPath), { recursive: true });
  try {
    const st = await lstat(linkPath);
    if (st.isSymbolicLink()) {
      const existingTarget = await readlink(linkPath);
      if (existingTarget === target) return;
      await unlink(linkPath);
    } else {
      throw new Error(`${linkPath} already exists and is not a symlink claude-sync manages — remove it manually first`);
    }
  } catch (err: any) {
    if (err.code !== "ENOENT") throw err;
  }
  await symlink(target, linkPath);
}

/** Write (or repair) a generated, executable wrapper script at destPath. Refuses to touch
 * a real file/symlink that isn't already ours — recognized either by the sentinel comment
 * (current wrapper format) or, for a smooth upgrade from older installs, a symlink whose
 * target path contains "claude-sync". */
async function ensureOwnedExecutable(destPath: string, contents: string): Promise<void> {
  await mkdir(dirname(destPath), { recursive: true });
  try {
    const st = await lstat(destPath);
    if (st.isSymbolicLink()) {
      const target = await readlink(destPath);
      if (!target.includes("claude-sync")) {
        throw new Error(`${destPath} already exists and is not a symlink claude-sync manages — remove it manually first`);
      }
      await unlink(destPath); // legacy symlink from an older install; replaced with a generated wrapper below
    } else {
      const existing = await readFile(destPath, "utf8").catch(() => "");
      if (!existing.includes(WRAPPER_SENTINEL)) {
        throw new Error(`${destPath} already exists and is not a file claude-sync manages — remove it manually first`);
      }
    }
  } catch (err: any) {
    if (err.code !== "ENOENT") throw err;
  }
  const tmp = `${destPath}.tmp.${process.pid}`;
  await writeFile(tmp, contents, { mode: 0o755 });
  await rename(tmp, destPath);
}

export async function install(overrides: Partial<InstallPaths> = {}): Promise<void> {
  const p = { ...defaultInstallPaths(), ...overrides };

  let raw: string;
  try {
    raw = await readFile(p.settingsPath, "utf8");
  } catch {
    raw = "{}";
  }
  let settings: Record<string, unknown>;
  try {
    settings = JSON.parse(raw);
  } catch (err) {
    throw new Error(`Refusing to install: ${p.settingsPath} is not valid JSON (${err}). Fix or remove it, then retry.`);
  }

  const next = mergeHooks(settings, p.hookMainPath, p.bunPath);
  await backupAndWriteSettings(p.settingsPath, next);

  await ensureSymlink(p.skillSrcDir, p.skillDestDir);
  await ensureOwnedExecutable(join(p.localBinDir, "claude-sync"), claudeSyncWrapperContents(p.bunPath, p.repoRoot));
  await ensureOwnedExecutable(join(p.localBinDir, "csync"), csyncWrapperContents(p.localBinDir));

  await mkdir(paths.root(), { recursive: true });

  console.log("claude-sync installed.");
  console.log(`Hooks merged into ${p.settingsPath} (a backup was saved alongside it).`);
  console.log(`Skill linked at ${p.skillDestDir}`);
  console.log(`Binaries generated in ${p.localBinDir} (csync, claude-sync)`);
}
